### ISSUE TITLE
Crash when used on server

### ISSUE THREAD

**Issue by calloatti** [MrIbby/shulker-bag#1]
These versions:

![image](https://user-images.githubusercontent.com/12817862/58713873-e95e0a00-8399-11e9-94c5-66243a6d392a.png)

Mods Folder:

fabric-api-0.3.0+build.175.jar
shulker-bag-1.0.0.jar

Log: https://paste.ee/p/EjkeS

**Comment by Shnupbups** [comment]
This is due to an attempt to mixin to the `AbstractContainerScreen` class, which is Client side only.
The crash can be fixed by marking the mixin as Client Only.

**Comment by Shnupbups** [comment]
Fixed by #2

**Comment by MrIbby** [comment]
Here's the new release https://github.com/MrIbby/shulker-bag/releases/tag/v1.0.1

Thanks Shnupbups! (And thanks calloatti for reporting!)
